const LOAD_USER_POSTS = "LOAD_USER_POSTS";
const LOAD_ACTIVE_USER = "LOAD_ACTIVE_USER";
const POSTS_ARE_LOADING = "POSTS_ARE_LOADING";
const USER_IS_LOADING = "USER_IS_LOADING";
const TOGGLE_CONTACT_STATUS = "TOGGLE_CONTACT_STATUS";
const GET_POST_COMMENTS_USER = "GET_POST_COMMENTS_USER";
const CLOSE_MODAL = "CLOSE_MODAL";
const OPEN_MODAL = "OPEN_MODAL";

export default {
    LOAD_USER_POSTS,
    LOAD_ACTIVE_USER,
    POSTS_ARE_LOADING,
    USER_IS_LOADING,
    TOGGLE_CONTACT_STATUS,
    GET_POST_COMMENTS_USER,
    CLOSE_MODAL,
    OPEN_MODAL,
}