const GET_ALL_USERS_POSTS = "GET_ALL_USERS_POSTS";
const CLEAR_ALL_USERS_POSTS = "CLEAR_ALL_USERS_POSTS";
const LOAD_USER_POSTS = "LOAD_USER_POSTS";
const SET_ACTIVE_USER = "SET_ACTIVE_USER";
const LOAD_CURRENT_USER = "LOAD_CURRENT_USER";
const POSTS_ARE_LOADING = "POSTS_ARE_LOADING";
const USER_IS_LOADING = "USER_IS_LOADING";
const TOGGLE_CONTACT_STATUS = "TOGGLE_CONTACT_STATUS";
const GET_POST_COMMENTS_USER = "GET_POST_COMMENTS_USER";
const CLOSE_MODAL = "CLOSE_MODAL";
const OPEN_MODAL = "OPEN_MODAL";
const POST_NEW_COMMENT = "POST_NEW_COMMENT";
const UPDATE_LIKE_STATUS = "UPDATE_LIKE_STATUS";

export default {
    GET_ALL_USERS_POSTS,
    CLEAR_ALL_USERS_POSTS,
    LOAD_USER_POSTS,
    SET_ACTIVE_USER,
    LOAD_CURRENT_USER,
    POSTS_ARE_LOADING,
    USER_IS_LOADING,
    TOGGLE_CONTACT_STATUS,
    GET_POST_COMMENTS_USER,
    CLOSE_MODAL,
    OPEN_MODAL,
    POST_NEW_COMMENT,
    UPDATE_LIKE_STATUS,
}